name: gesture_to_voice
description: An app that reads a gesture from a camera input and outputs the message in a voice

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_tts: ^3.3.3
  camera: ^0.9.4+5
  flutter_spinkit: ^5.1.0
  provider: ^6.0.2
  translator: ^0.1.7
  tflite: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/model/
    - assets/flags/

  fonts:
    - family: SFBold
      fonts:
        - asset: assets/fonts/SFBold.otf
    - family: SFRegular
      fonts:
        - asset: assets/fonts/SFRegular.otf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
